#spring.profiles.active: local
server:
  port: 80
  #ssl:
  #  enabled: true # Uses self-signed certificate because no key-store configuration is specified.

internal.lb.uri: http://ip-de-tu-maquina-virtual
spring:
  cloud:
    gateway:
      routes:
        - id: jugadores
          uri: http://backend:9000
          predicates:
            - Path=/api/listaJugadores/**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}
        - id: apostadores
          uri: http://backend:9000
          predicates:
            - Path=/api/listaApostadores/**
          filters:
            - RewritePath=/api/listaJugadores/(?<path>.*), /$\{path}
        - id: apuestas
          uri: http://backend:9000
          predicates:
            - Path=/api/listaApuestas/**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}
        - id: frontend
          uri: http://frontend:9001
          predicates:
            - Path=/**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}